### ISSUE TITLE
Raspberry Pi Zero 2

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixcon2023-sbc-giveaway#3]
Comes with:
* Case: https://www.aliexpress.com/item/1005003843166619.html
* power supply / ethernet adapter thing: allows you to power it and provide USB Ethernet connection in just the secondary micro-B port

I also have like one or two spare Flirc cases that I can toss in if you want for some reason...

**Comment by samueldr** [comment]
Impossible to get, and is basically the last "not broken" raspberry pi SBC they launched.
