### ISSUE TITLE
StarFive: VisionFive 1

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixcon2023-sbc-giveaway#6]
Comes with:
* acrylic case
* some semi-usable uboot written to flash, probably some old attempt at a franken tow-boot build

No:
* power supply (I can't remember but I think generic USB-C power supplies should work. I know that's a vague overloaded statement, sorry.)

**Comment by samueldr** [comment]
Depending on discussion, either this or #7, also depending on the boot chain; if they are the same, any of them
