### ISSUE TITLE
Lichee Pi 4A

### ISSUE THREAD

**Issue by colemickens** [colemickens/nixcon2023-sbc-giveaway#8]
I didn't know it when I bought it, but I bought a slightly "early" variant, I guess?

It's the 8GB+8GB model (so 8GB eMMC, 8GB DDR)

Comes with:
- power supply
- fan
- cheapo wifi attennas (not the nice screw in ones you seem to get with it now on AliExpress

**Comment by samueldr** [comment]
For Tow-Boot support, mainly, and "trivial" NixOS support.

As long as the boot chain is not broken compared to less early variant, it would be the same.
